# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'shopTogether' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for shopTogether
    pod 'Alamofire'
    pod 'FSPagerView'
    pod 'Apollo'

  target 'shopTogetherTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'shopTogetherUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
